version: '3'

services:

  web:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - 8000:80
    depends_on:
      - app

  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.docker/volumes/postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - ./src:/var/www
    depends_on:
      - db
